# Generated by Django 6.0 on 2025-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название рецепта"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "ingredients",
                    models.TextField(
                        help_text="Каждый ингредиент с новой строки",
                        verbose_name="Ингредиенты",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(verbose_name="Инструкция по приготовлению"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recipes/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Время приготовления (минуты)"
                    ),
                ),
                (
                    "servings",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Количество порций"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Легко"),
                            ("medium", "Средне"),
                            ("hard", "Сложно"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
            ],
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
                "ordering": ["-created_at"],
            },
        ),
    ]
